/*
 * Generates everything the Worker needs that already exists at the repo root,
 * so nothing is committed twice and the two copies cannot drift.
 *
 *   assets/, fonts/  ->  worker/public/   (served via the ASSETS binding)
 *   js/persian-numbers.js -> worker/src/lib/persianNumbers.js  (ESM wrapper)
 *
 * All of the generated targets are gitignored. Run before dev / deploy /
 * tests, which the package.json scripts already do.
 */
import { cp, mkdir, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const workerRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(workerRoot, "..");

const PAIRS = [
  ["assets", "public/assets"],
  ["fonts", "public/fonts"],
];

for (const [from, to] of PAIRS) {
  const source = path.join(repoRoot, from);
  const target = path.join(workerRoot, to);
  await mkdir(target, { recursive: true });
  await cp(source, target, { recursive: true });
  console.log(`synced ${from}/ -> worker/${to}/`);
}

/*
 * The number library is one file, and it is the root one. It has to stay a
 * classic script there — index.html loads it with a plain <script> tag so the
 * app keeps working when opened directly via file://, where ES module
 * resolution is blocked — while the Worker needs named ESM exports. So the
 * Worker's copy is the same source text plus a generated export footer.
 *
 * The name list is read off the module's own exports rather than written out
 * here, so adding a function to the root file is all it takes.
 */
const numbersSource = path.join(repoRoot, "js", "persian-numbers.js");
const numbersTarget = path.join(workerRoot, "src", "lib", "persianNumbers.js");
const { default: PersianNumbers } = await import(pathToFileURL(numbersSource).href);
const names = Object.keys(PersianNumbers);
const banner =
  "/* GENERATED by worker/scripts/sync-assets.mjs from js/persian-numbers.js.\n" +
  " * Do not edit; edit the root file instead. */\n";
// Re-exports the existing top-level declarations rather than destructuring
// PersianNumbers, which would redeclare every one of those names.
const footer = [
  "",
  "// Generated ESM surface (see scripts/sync-assets.mjs).",
  "export {",
  ...names.map((name) => `  ${name},`),
  "};",
  "",
].join("\n");
await mkdir(path.dirname(numbersTarget), { recursive: true });
await writeFile(numbersTarget, banner + readFileSync(numbersSource, "utf8") + footer, "utf8");
console.log(`generated js/persian-numbers.js -> worker/src/lib/persianNumbers.js (${names.length} exports)`);
