/*
 * Generates everything the Worker needs that already exists at the repo root,
 * so nothing is committed twice and the two copies cannot drift.
 *
 *   assets/, fonts/  ->  worker/public/   (served via the ASSETS binding)
 *   js/persian-numbers.js -> worker/src/lib/persianNumbers.js  (ESM wrapper)
 *
 * All of the generated targets are gitignored. Run before dev / deploy /
 * tests, which the package.json scripts already do.
 */
import { cp, mkdir, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const workerRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(workerRoot, "..");

const PAIRS = [
  ["assets", "public/assets"],
  ["fonts", "public/fonts"],
];

for (const [from, to] of PAIRS) {
  const source = path.join(repoRoot, from);
  const target = path.join(workerRoot, to);
  await mkdir(target, { recursive: true });
  await cp(source, target, { recursive: true });
  console.log(`synced ${from}/ -> worker/${to}/`);
}

/*
 * The shared libraries are single files, and the root copies are the real
 * ones. They have to stay classic scripts there — index.html loads them with
 * plain <script> tags so the app keeps working when opened directly via
 * file://, where ES module resolution is blocked — while the Worker needs
 * named ESM exports. So each Worker copy is the same source text with a
 * generated import prologue and export footer wrapped around it.
 *
 * Each name list is read off the module's own exports rather than written out
 * here, so adding a function to a root file is all it takes.
 *
 * `imports` names the sibling generated modules whose top-level functions this
 * one calls. A classic script gets them from global scope for free; the ESM
 * copy has to say so.
 */
const SHARED_MODULES = [
  { source: "js/persian-numbers.js", target: "src/lib/persianNumbers.js", imports: [] },
  { source: "js/invoice-totals.js", target: "src/lib/invoiceTotals.js", imports: ["./persianNumbers.js"] },
];

// Specifier -> the names that copy exports, filled in as each one is written.
// Read from the root modules rather than by importing the generated files:
// those carry ESM syntax into a directory Node treats as CommonJS.
const generatedExports = new Map();

for (const { source, target, imports } of SHARED_MODULES) {
  const sourcePath = path.join(repoRoot, source);
  const targetPath = path.join(workerRoot, target);
  const { default: exported } = await import(pathToFileURL(sourcePath).href);
  const names = Object.keys(exported);

  const banner =
    `/* GENERATED by worker/scripts/sync-assets.mjs from ${source}.\n` +
    " * Do not edit; edit the root file instead. */\n";

  // Pulled in by name so the bundler can see them. The root file reaches these
  // through global scope, which only exists under a <script> tag.
  const prologue = imports.length
    ? imports.map((specifier) => {
        const depNames = generatedExports.get(specifier);
        if (!depNames) throw new Error(`${source} imports ${specifier}, which is not generated before it`);
        return `import {\n${depNames.map((n) => `  ${n},`).join("\n")}\n} from "${specifier}";\n`;
      }).join("") + "\n"
    : "";

  // Re-exports the existing top-level declarations rather than destructuring
  // the namespace object, which would redeclare every one of those names.
  const footer = [
    "",
    "// Generated ESM surface (see scripts/sync-assets.mjs).",
    "export {",
    ...names.map((name) => `  ${name},`),
    "};",
    "",
  ].join("\n");

  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, banner + prologue + readFileSync(sourcePath, "utf8") + footer, "utf8");
  generatedExports.set(`./${path.basename(target)}`, names);
  console.log(`generated ${source} -> worker/${target} (${names.length} exports)`);
}
